### ISSUE TITLE
Manager App 마무리 전 해결해야 할 것들

### ISSUE THREAD

**Issue by codeforchoi** [alexization/foodycode#160]
- [ ] 매니저 로그인 화면 UI 디자인 나오는대로 변경
- [x] 회원가입 약관동의 Accept를 동의로 바꾸기
- [x] 회원가입 Confirm 버튼 기능 추가 
- [x] 회원가입 한글화
- [x] 회원가입 비밀번호 confirm 기능 넣어야함
- [x] 회원가입 다 입력되면 버튼 활성화
- [x] 회원가입 버튼 Next -> 등록하기 로 바꾸기
- [x] 매니저 메인화면 사이드바 로그아웃 만들기 #162 
- [x] 매니저 메인화면 div들 늘려놓지 말고 붙이기 #162
- [x] 매니저 로그인 화면 뒤로가기 기능 제거 #162
- [x] 매니저 로그인 한글화 및 모달 한글화 #165 
- [ ] 메뉴관리화면에서 사용자 메뉴 상세페이지로 누르면 가질 수 있도록( 수정버튼 안눌렀을 때) 백엔드 작업 필요
- [x] 메뉴관리화면에서 + 버튼을 위에 보이도록 설정 #165 
- [x] index.js View 페이지명 설정 #165
- [x] EditMenuDetail.vue View 페이지 생성 #165
- [x] EditMenu.vue 메뉴 상세페이지 라우터 기능 추가 #165
- [ ] EditMenu.vue 페이지 수정 버튼 누르면 메뉴 추가 버튼 보이게 설정 위치는 수정 버튼 아래에 위치
- [ ] EditMenuDetail.vue 페이지 order버튼만 비활성화 나머지는 모두 보이도록 설정
- [ ] 메뉴 상세 페이지 Default Roman name 없애기 (매니저 앱, 사용자 앱 모두)
- [ ] 매니저 로그인 화면 아이디 찾기, 비밀번호 찾기 모달 문구 (회의 필요)
- [ ] 이미지 업로드 기능 추가
- [ ] 매니저 사이드바 기능 logout 백엔드 작업
- [ ] 오류 발견: 매니저로 로그인해도 사용자 화면에서 이름이 뜨지는 않아도 사이드바에 로그인되있는 메뉴가 뜹니다.
